### ISSUE TITLE
QUOTA_BYTES_PER_ITEM quota exceeded

### ISSUE THREAD

**Issue by djinntwo** [DaniloNovakovic/chrome-dynamic-bookmarks#34]
I seem to have reached the limit on how many dynamic bookmarks I can have. If I try to create more then 18 then I get a "QUOTA_BYTES_PER_ITEM quota exceeded" error. Deleting a bookmark allows the creation of a new one but still is limited to 18.

version 2.5.0 on Chrome 76.0.3809.100 (Official Build) (64-bit)
Windows 10 Pro 64bit version 1903 (OS Build 18362.295)

**Comment by DaniloNovakovic** [comment]
@djinntwo Thanks for reporting this issue. Limiting users to be able to track only 18 bookmarks was not my intent and I will try to correct it as soon as possible.

**Comment by DaniloNovakovic** [comment]
#35 seems to have fixed this issue. The release will be publicly available on the Chrome store in few days once additional tests are performed to make sure everything is working correctly. Thank you for your patience. 😊
